services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - network1

  auth-service:
    build: .
    container_name: auth-service
    environment:
      PORT: 4001
      JWT_SECRET: A1B2C3
      MONGO_URL: mongodb://root:example@mongodb:27017/auth-service?authSource=admin
    ports:
      - "4001:4001"
    depends_on:
      - mongodb
    networks:
      - network1
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    environment:
      - DOCKER_HOST=tcp://docker:2376
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"
    networks:
      - network1

networks:
  network1:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
  jenkins_home:  